theme: jekyll-theme-cayman
title: Sociedad Civil Cuba (repositorio)
logo: "https://avatars0.githubusercontent.com/u/65537970?s=460&u=c88108e99c54f5608103a80bc12b9a1807b33ce2&v=4"
show_downloads: "true"
